import directory from "@/data/vso-directory.json";

// THE ACCREDITED-REPRESENTATIVE LOOKUP.
//
// Data is VA's Office of General Counsel's own published accreditation lists,
// regenerated by scripts/build-vso-directory.cjs. See that file for the three
// traps in the source format.
//
// WHY THIS IS SAFE TO HOST, given the standing rule that a stale directory is
// worse than no directory: the payload carries the date it was generated, the
// UI prints that date, and every result ends by pointing at VA's own live
// search. A veteran is never told this list is current — he is shown when it
// was taken and given the authoritative place to confirm.
//
// WHAT THIS NEVER DOES: rank, score, recommend, or rate a representative.
// It reports who VA accredits near a ZIP code, free options first because
// they are free, and says plainly that this app has no relationship with any
// of them. Choosing a representative is the veteran's decision.

export type RepKind = "vso" | "attorney" | "agent";

type RawEntry = { o: string; p: string; c: string; s: string; z: string; n: number; t: string };

export type VsoResult = {
  name: string;
  phone: string | null;
  city: string;
  state: string;
  zip: string;
  /** How many accredited representatives this organization has at this ZIP. */
  reps: number;
  kind: RepKind;
  /** True when this sits in the exact ZIP the veteran typed. */
  exact: boolean;
};

export type VsoSearch =
  | { status: "ok"; scope: "exact" | "nearby"; zip: string; results: VsoResult[]; generated: string }
  | { status: "none"; zip: string; generated: string }
  | { status: "invalid" };

const DATA = directory as unknown as {
  generated: string;
  byZip3: Record<string, RawEntry[]>;
};

export const DIRECTORY_GENERATED = DATA.generated;

/** Free help first. This is the only ordering opinion the app expresses, and
 *  it is a fact about cost, not a judgement about quality. */
const KIND_RANK: Record<string, number> = { vso: 0, agent: 1, attorney: 2 };

export function searchVso(rawZip: string, limit = 40): VsoSearch {
  const zip = (rawZip ?? "").trim().slice(0, 5);
  if (!/^\d{5}$/.test(zip)) return { status: "invalid" };

  const bucket = DATA.byZip3[zip.slice(0, 3)] ?? [];
  if (bucket.length === 0) {
    return { status: "none", zip, generated: DATA.generated };
  }

  const mapped: VsoResult[] = bucket.map((e) => ({
    name: e.o,
    phone: e.p || null,
    city: e.c,
    state: e.s,
    zip: e.z,
    reps: e.n,
    kind: (KIND_RANK[e.t] !== undefined ? e.t : "vso") as RepKind,
    exact: e.z === zip,
  }));

  const exactHits = mapped.filter((r) => r.exact);

  // Widen to the ZIP3 area if the exact ZIP has nothing — OR if it has
  // nothing FREE.
  //
  // That second condition is the important one and it came out of testing,
  // not theory: ZIP 89101 in downtown Las Vegas is registered to five
  // accredited attorneys and not one Veterans Service Organization. Showing
  // a veteran that exact-ZIP list would hand him five people who may charge
  // a fee and imply those are his options — when DAV, the American Legion
  // and Nevada's state office all serve Las Vegas for free from neighbouring
  // ZIPs. An app whose central promise is "a VSO is free, every time" cannot
  // lead with the paid list because of a postcode boundary.
  const exactHasFree = exactHits.some((r) => r.kind === "vso");
  const useExact = exactHits.length > 0 && exactHasFree;
  const pool = useExact ? exactHits : mapped;
  const scope: "exact" | "nearby" = useExact ? "exact" : "nearby";

  pool.sort(
    (a, b) =>
      KIND_RANK[a.kind] - KIND_RANK[b.kind] ||
      Number(b.exact) - Number(a.exact) ||
      b.reps - a.reps ||
      a.name.localeCompare(b.name),
  );

  return { status: "ok", scope, zip, results: pool.slice(0, limit), generated: DATA.generated };
}
