-- 0033 — cached place profiles for the "background on this place" panel.
--
-- WHAT THIS REPLACES. /api/base-info asked the model to write a short history of
-- a place every single time a veteran opened a logged location. "Camp Lejeune"
-- was regenerated from scratch for every man who ever served there. Two problems
-- with that, and the second is the one that actually matters.
--
--   1. Cost. It is the same answer every time, paid for every time.
--   2. ACCURACY, which is worse. That prompt forbids inventing dates, units and
--      events — because a profile of a place a veteran served is a thing he will
--      believe. Regenerating it per request means a fabricated detail can appear
--      for one man and not the next, so nobody can ever catch it, and there is
--      nothing to correct even if somebody does. A stored profile is read once,
--      checked once, and FIXED once for everybody.
--
-- WHY THIS TABLE IS READ-ONLY, and why that is not negotiable.
--
-- This app holds no service-role key, on purpose (pre-launch audit, finding #2).
-- Every query — from the browser AND from the route handlers — runs with the
-- publishable key that ships in the bundle. So there is no policy that lets the
-- SERVER write here without also letting any signed-in veteran write here, by
-- POSTing straight to /rest/v1/place_profiles.
--
-- That would be a content-poisoning hole: this is shared text that every
-- veteran reads, attributed to the app. One bad actor writing a slur or a
-- falsehood into a place every Marine of a certain era served at would be read
-- by all of them, as ours.
--
-- So: SELECT only, and no INSERT/UPDATE/DELETE policy at all. RLS denies by
-- default, so the absence of a policy IS the control — do not add a write
-- policy here to make something convenient. Rows arrive the way the exposure
-- sites do: as a reviewed seed migration, generated by
-- scripts/build-place-profiles.cjs and read by a human before it is applied.
--
-- A place with no row simply falls through to the live model call that exists
-- today, rate-limited as before. The cache is an optimisation, never a gate.

create table if not exists place_profiles (
  id           uuid primary key default gen_random_uuid(),
  -- The lookup key: lowercased, trimmed, inner whitespace collapsed. Matching
  -- happens on this, never on display_name, so "Camp  Lejeune " and
  -- "camp lejeune" are the same place.
  name_key     text not null unique,
  -- The name as it was generated for, kept so a reviewer can see what was asked
  -- rather than reverse-engineering it from the key.
  display_name text not null,
  profile      text not null,
  -- Which model wrote it, so a future re-generation can tell what is stale.
  model        text,
  -- Set true only by a human who has read it. Nothing is served unless this is
  -- true — see the policy below. An unreviewed row is inert.
  reviewed     boolean not null default false,
  created_at   timestamptz not null default now(),
  reviewed_at  timestamptz
);

create index if not exists place_profiles_key_idx on place_profiles (name_key) where reviewed;

alter table place_profiles enable row level security;

-- Signed-in members may READ reviewed profiles. That is the whole policy.
-- There is deliberately no write policy of any kind; see the header.
create policy place_profiles_read on place_profiles for select
  using ((select auth.uid()) is not null and reviewed);
